import { z } from 'zod';

export const ScoreSubmissionSchema = z.object({
  previous_ref: z.string().trim().max(50).optional(),
  nom_fondateur: z.string().trim().min(2).max(100),
  email: z.string().email().max(254),
  pays: z.string().trim().min(2).max(100),
  ville: z.string().trim().min(2).max(100),
  nom_startup: z.string().trim().min(2).max(100).regex(/^[\p{L}\p{N}\s\-'.&]+$/u),
  pitch_une_phrase: z.string().trim().min(5).max(300),
  probleme: z.string().trim().min(20).max(2000),
  solution: z.string().trim().min(20).max(2000),
  secteur: z.enum([
    'fintech', 'healthtech', 'saas', 'marketplace', 'deeptech',
    'greentech', 'edtech', 'proptech', 'legaltech', 'foodtech',
    'mobility_logistics', 'media_entertainment', 'hr_recruiting',
    'cybersecurity', 'insurtech', 'biotech', 'agritech',
    'social_impact', 'ai_ml_native', 'web3_blockchain',
    'space_defense', 'other'
  ]),
  type_client: z.enum(['b2b', 'b2c', 'b2b2c', 'b2g', 'other']),
  tam_usd: z.enum(['100K', '500K', '1M', '5M', '10M', '50M', '100M', '500M', '1B', '5B', '10B']),
  estimation_tam: z.string().trim().min(20).max(2000),
  acquisition_clients: z.string().trim().min(20).max(2000),
  concurrents: z.string().trim().min(20).max(2000),
  moat: z.string().trim().min(20).max(2000),
  stade: z.enum(['idea', 'pre-seed', 'mvp', 'seed', 'serieA', 'serieB_plus']),
  revenus: z.enum(['oui', 'non']),
  mrr: z.number().nonnegative().max(100_000_000).optional(),
  clients_payants: z.number().int().nonnegative().max(1_000_000).optional(),
  pourquoi_vous: z.string().trim().min(20).max(2000),
  equipe_temps_plein: z.enum(['oui', 'non']),
  priorite_6_mois: z.string().trim().min(20).max(1000),
  montant_leve: z.enum(['25K', '50K', '100K', '150K', '250K', '500K', '750K', '1M', '1.5M', '2M', '3M', '5M', '10M', '20M', '50M+']),
  jalons_18_mois: z.string().trim().min(20).max(2000),
  utilisation_fonds: z.string().trim().min(20).max(2000),
  vision_5_ans: z.string().trim().min(20).max(2000),
  autres_informations: z.string().trim().max(3000).optional(),
  linkedin_url: z.string().url().max(500).optional(),
  site_url: z.string().url().max(500).optional(),
  pitch_deck_base64: z.string().min(1).max(15_000_000),
  pitch_deck_filename: z.string().max(200).regex(/\.pdf$/i, 'Le pitch deck doit être au format PDF.'),
  doc_supplementaire_url: z.string().url().max(500).optional(),
}).strip();
